version: "3.8"

services:
  openresty:
    build: ./openresty
    ports:
      - "8080:80"  # Mapeia a porta 80 do container para a porta 8080 do host
    networks:
      - app-network

  lapis:
    build: ./lapis
    volumes:
      - ../App:/App  # Mapeia o diretório local "lua_app" para /app no container
    ports:
      - 3000:3000
    networks:
      - app-network
    command: ["lapis", "server"]

networks:
  app-network:
    driver: bridge
